### ISSUE TITLE
Build job posting form

### ISSUE THREAD

**Issue by pacarole** [codeforamerica/nola-2016-fellows#56]
Build form to serve as test for job posting tool

Blocked at least partially by #55 (Prompts)
**Not** blocked by #61 (Design)
- [ ] @pacarole and @antislice need to discuss extending existing tool vs. greenfield (aka is this still a fork of joblint)

Can be split up further if some prompts are more intensive than others.

**Comment by antislice** [comment]
This issue was moved to antislice/api-test#34

**Comment by antislice** [comment]
This issue was moved to codeforamerica/joblint#43
