### ISSUE TITLE
Explore pushing job postings to LAWorks

### ISSUE THREAD

**Issue by pacarole** [codeforamerica/nola-2016-fellows#58]
Figure out what the technical work required to push job postings to Louisiana Works would be.

**Comment by antislice** [comment]
LAWorks scrapes postings from other sites, easy if we don’t necessarily want to associate a registered employer. (what happens if it scrapes a posting from a registered employer, does that get matched up?)

**Comment by antislice** [comment]
Removed from milestone because it seems like a stretch goal or MVP feature.

**Comment by antislice** [comment]
This issue was moved to codeforamerica/joblint#37
