### ISSUE TITLE
Find out when upcoming foundational trainings are

### ISSUE THREAD

**Issue by antislice** [codeforamerica/nola-2016-fellows#66]
Call OCs:
- [x] Job1
- [x] TCA
- [x] STRIVE
- [x] Urban League
- [ ] Goodwill

Dates for the next 2-3 (or the recurrence) would be good.

**Comment by skcain** [comment]
_Total Community Action_
Hours: 8am – 6pm (Mon-Thurs) 8-4 (Friday)
Foundational Skills Training: May 9th - June 3rd (Mon-Fri 9 – 1)

_STRIVE NOLA_ 504-658-4201
Hours: 9am - 5pm (M-F)
Foundational Skills Training: Registration: April 11th - May 9th. TABE testing May 9th - May 12th. Orientation May 13th.

_Job1_
Hours: 8am - 5pm (Mon, Tu, Wed, Fri), 8am - 3pm Thu
Foundational Skills Training: Have to come in and register

_Urban League_
Hours: 8:30 – 5 (Mon-Fri)
Foundational Skills Training:
Info session: March 31st 10am

_Goodwill_
Hours: 8am - 4:30pm (Mon-Th) 8am - 2:30pm (Fri)
Foundational Skills Training: Got pushed to JOB1

**Comment by pacarole** [comment]
https://docs.google.com/spreadsheets/d/1fLsD5YpuLgcOEfok-0g2zImY1rvpAH5iW5ATTyskQvc/edit
