### ISSUE TITLE
Create public google calendar for OC trainings

### ISSUE THREAD

**Issue by antislice** [codeforamerica/nola-2016-fellows#67]
Can we do different colors for different OC trainings?

**Comment by antislice** [comment]
but where's the link to it @pacarole :smile:

**Comment by pacarole** [comment]
https://calendar.google.com/calendar/embed?src=codeforamerica.org_rufvrvb13drksb10nusd2fd4ms%40group.calendar.google.com&ctz=America/Los_Angeles

**Comment by pacarole** [comment]
This is on hold until we figure out what the deal is w/ the OC Skills Training spreadsheet.
