### ISSUE TITLE
distribute shared calendar ✨

### ISSUE THREAD

**Issue by antislice** [codeforamerica/nola-2016-fellows#71]
Might get the best reception if we get Tanya to send it out.

**Comment by antislice** [comment]
Current plan: talk to Shawn about him sharing his document with outreach partners via Ameca. Followup/measuring would be via short survey right before we come back, talking to people.

**Comment by pacarole** [comment]
Shawn is on board with sending this out. We just need Ameca to distribute it and to do follow up.
